name: git_task
description: GitTask - A task management app with Git concepts
publish_to: 'none'
version: 1.0.2-1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State management
  provider: ^6.0.5
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  
  # UUID generation
  uuid: ^3.0.7
  
  # Date time formatting
  intl: ^0.18.0
  
  # Chart rendering
  fl_chart: ^0.62.0
  
  # Network
  http: ^1.1.0
  url_launcher: ^6.1.14
  package_info_plus: ^4.1.0
  
  # Dynamic theming
  dynamic_color: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true